
# 📘 Experiment Log : Assignment 2 - PyTorch.ipynb

- 🗓️ 과제 수행일: 2025.05.15 ~ 2025.05.21
- ⏱️ 정리일: 2025.05.21
- 🧠 목적: 파이토치 실습 및 CIFAR-10 classification

---

## 1. 📂 Dataset & Task
- 사용한 데이터셋: CIFAR-10
- Task 유형: 분류
- Input 형태: 이미지(32x32)
- Output 형태: 클래스 라벨

---

## 2. 🧪 실험 내용 요약

- ### 모델 구조

 - **Residual Block × 5**  
  Each block consists of:  
  `Conv → ReLU → Conv → (+ Identity) → ReLU`

 - **Fully Connected Layers**  
  `→ Flatten → FC → ReLU → Dropout → FC → Softmax`


- ### Training Settings

 - Optimizer: SGD + Nesterov Momentum  
 - Learning Rate: `3e-3`  
 - Weight Decay (L2 Regularization): `1e-3`  
 - Dropout Probability: `0.5`  
 - Epochs: `15`  
 - Batch Normalization: Applied after each Conv in residual blocks


---

## 3. 📊 실험 결과

- **Validation Accuracy : 85.00%**
- **Test Accuracy : 83.27%**
---

## 4. 🔍 해석 및 인사이트

- PyTorch에는 nn.Module 또는 nn.Sequential을 사용하여 딥러닝 모델을 쉽게 구현할 수 있음.
- nn.Module은 nn.Sequential 보다는 덜 간단하지만 유연성이 높다는 장점을 가지고 있음.
- nn.Sequential을 사용하면 매우 간단하게 코드를 작성할 수 있지만 유연성이 다소 떨어지며 만들 수 있는 구조에 한계가 있음.

---

## 5. 💬 한 줄 회고
- 그동안 이론 위주로 공부를 해왔고 직접 구현을 해보더라도 PyTorch 없이 코드를 작성하는 실습이 대부분이었는데, 처음으로 PyTorch 사용법을 알게 되어서 한 단계 성장한 기분이 들었다. 또한 PyTorch를 자유롭게 활용하여 나만의 모델을 만드는 과정이 매우 흥미로웠다. 과제 내에서 epoch을 최대 15로 제한하고 있는데, 이 제한이 없었다면 성능을 조금 더 향상시킬 수 있었을 것 같다. 시간만 충분했다면 조금 더 다양한 구조의 모델을 실험해보고, regularization strength도 grid search 등을 통해 조정해봤을 것 같다.
---



In [1]:
# This mounts your Google Drive to the Colab VM.
from google.colab import drive
drive.mount('/content/drive')

# TODO: Enter the foldername in your Drive where you have saved the unzipped
# assignment folder, e.g. 'cs231n/assignments/assignment2/'
FOLDERNAME = 'Colab_Notebooks/cs231n/cs231n_assignment2/'
assert FOLDERNAME is not None, "[!] Enter the foldername."

# Now that we've mounted your Drive, this ensures that
# the Python interpreter of the Colab VM can load
# python files from within it.
import sys
sys.path.append('/content/drive/My Drive/{}'.format(FOLDERNAME))

# This downloads the CIFAR-10 dataset to your Drive
# if it doesn't already exist.
%cd /content/drive/My\ Drive/$FOLDERNAME/cs231n/datasets/
!bash get_datasets.sh
%cd /content/drive/My\ Drive/$FOLDERNAME

Mounted at /content/drive
/content/drive/My Drive/Colab_Notebooks/cs231n/cs231n_assignment2/cs231n/datasets
/content/drive/My Drive/Colab_Notebooks/cs231n/cs231n_assignment2


# Introduction to PyTorch

You've written a lot of code in this assignment to provide a whole host of neural network functionality. Dropout, Batch Norm, and 2D convolutions are some of the workhorses of deep learning in computer vision. You've also worked hard to make your code efficient and vectorized.

For the last part of this assignment, though, we're going to leave behind your beautiful codebase and instead migrate to one of two popular deep learning frameworks: in this instance, PyTorch.

## Why do we use deep learning frameworks?

* Our code will now run on GPUs! This will allow our models to train much faster. When using a framework like PyTorch you can harness the power of the GPU for your own custom neural network architectures without having to write CUDA code directly (which is beyond the scope of this class).
* In this class, we want you to be ready to use one of these frameworks for your project so you can experiment more efficiently than if you were writing every feature you want to use by hand.
* We want you to stand on the shoulders of giants! PyTorch is an excellent frameworks that will make your lives a lot easier, and now that you understand their guts, you are free to use them :)
* Finally, we want you to be exposed to the sort of deep learning code you might run into in academia or industry.

## What is PyTorch?

PyTorch is a system for executing dynamic computational graphs over Tensor objects that behave similarly as numpy ndarray. It comes with a powerful automatic differentiation engine that removes the need for manual back-propagation.

## How do I learn PyTorch?

One of our former instructors, Justin Johnson, made an excellent [tutorial](https://github.com/jcjohnson/pytorch-examples) for PyTorch.

You can also find the detailed [API doc](http://pytorch.org/docs/stable/index.html) here. If you have other questions that are not addressed by the API docs, the [PyTorch forum](https://discuss.pytorch.org/) is a much better place to ask than StackOverflow.

# Table of Contents

This assignment has 5 parts. You will learn PyTorch on **three different levels of abstraction**, which will help you understand it better and prepare you for the final project.

1. Part I, Preparation: we will use CIFAR-10 dataset.
2. Part II, Barebones PyTorch: **Abstraction level 1**, we will work directly with the lowest-level PyTorch Tensors.
3. Part III, PyTorch Module API: **Abstraction level 2**, we will use `nn.Module` to define arbitrary neural network architecture.
4. Part IV, PyTorch Sequential API: **Abstraction level 3**, we will use `nn.Sequential` to define a linear feed-forward network very conveniently.
5. Part V, CIFAR-10 open-ended challenge: please implement your own network to get as high accuracy as possible on CIFAR-10. You can experiment with any layer, optimizer, hyperparameters or other advanced features.

Here is a table of comparison:

| API           | Flexibility | Convenience |
|---------------|-------------|-------------|
| Barebone      | High        | Low         |
| `nn.Module`     | High        | Medium      |
| `nn.Sequential` | Low         | High        |

# GPU

You can manually switch to a GPU device on Colab by clicking `Runtime -> Change runtime type` and selecting `GPU` under `Hardware Accelerator`. You should do this before running the following cells to import packages, since the kernel gets restarted upon switching runtimes.

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data import sampler

import torchvision.datasets as dset
import torchvision.transforms as T

import numpy as np

USE_GPU = True
dtype = torch.float32 # We will be using float throughout this tutorial.

if USE_GPU and torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

# Constant to control how frequently we print train loss.
print_every = 100
print('using device:', device)

using device: cuda


# Part I. Preparation

Now, let's load the CIFAR-10 dataset. This might take a couple minutes the first time you do it, but the files should stay cached after that.

In previous parts of the assignment we had to write our own code to download the CIFAR-10 dataset, preprocess it, and iterate through it in minibatches; PyTorch provides convenient tools to automate this process for us.

In [3]:
NUM_TRAIN = 49000

# The torchvision.transforms package provides tools for preprocessing data
# and for performing data augmentation; here we set up a transform to
# preprocess the data by subtracting the mean RGB value and dividing by the
# standard deviation of each RGB value; we've hardcoded the mean and std.
transform = T.Compose([
                T.ToTensor(),
                T.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
            ])

# We set up a Dataset object for each split (train / val / test); Datasets load
# training examples one at a time, so we wrap each Dataset in a DataLoader which
# iterates through the Dataset and forms minibatches. We divide the CIFAR-10
# training set into train and val sets by passing a Sampler object to the
# DataLoader telling how it should sample from the underlying Dataset.
cifar10_train = dset.CIFAR10('./cs231n/datasets', train=True, download=True,
                             transform=transform)
loader_train = DataLoader(cifar10_train, batch_size=64,
                          sampler=sampler.SubsetRandomSampler(range(NUM_TRAIN)))

cifar10_val = dset.CIFAR10('./cs231n/datasets', train=True, download=True,
                           transform=transform)
loader_val = DataLoader(cifar10_val, batch_size=64,
                        sampler=sampler.SubsetRandomSampler(range(NUM_TRAIN, 50000)))

cifar10_test = dset.CIFAR10('./cs231n/datasets', train=False, download=True,
                            transform=transform)
loader_test = DataLoader(cifar10_test, batch_size=64)

# Part II. Barebones PyTorch

PyTorch ships with high-level APIs to help us define model architectures conveniently, which we will cover in Part II of this tutorial. In this section, we will start with the barebone PyTorch elements to understand the autograd engine better. After this exercise, you will come to appreciate the high-level model API more.

We will start with a simple fully-connected ReLU network with two hidden layers and no biases for CIFAR classification.
This implementation computes the forward pass using operations on PyTorch Tensors, and uses PyTorch autograd to compute gradients. It is important that you understand every line, because you will write a harder version after the example.

When we create a PyTorch Tensor with `requires_grad=True`, then operations involving that Tensor will not just compute values; they will also build up a computational graph in the background, allowing us to easily backpropagate through the graph to compute gradients of some Tensors with respect to a downstream loss. Concretely if x is a Tensor with `x.requires_grad == True` then after backpropagation `x.grad` will be another Tensor holding the gradient of x with respect to the scalar loss at the end.

### PyTorch Tensors: Flatten Function
A PyTorch Tensor is conceptionally similar to a numpy array: it is an n-dimensional grid of numbers, and like numpy PyTorch provides many functions to efficiently operate on Tensors. As a simple example, we provide a `flatten` function below which reshapes image data for use in a fully-connected neural network.

Recall that image data is typically stored in a Tensor of shape N x C x H x W, where:

* N is the number of datapoints
* C is the number of channels
* H is the height of the intermediate feature map in pixels
* W is the height of the intermediate feature map in pixels

This is the right way to represent the data when we are doing something like a 2D convolution, that needs spatial understanding of where the intermediate features are relative to each other. When we use fully connected affine layers to process the image, however, we want each datapoint to be represented by a single vector -- it's no longer useful to segregate the different channels, rows, and columns of the data. So, we use a "flatten" operation to collapse the `C x H x W` values per representation into a single long vector. The flatten function below first reads in the N, C, H, and W values from a given batch of data, and then returns a "view" of that data. "View" is analogous to numpy's "reshape" method: it reshapes x's dimensions to be N x ??, where ?? is allowed to be anything (in this case, it will be C x H x W, but we don't need to specify that explicitly).

In [4]:
def flatten(x):
    N = x.shape[0] # read in N, C, H, W
    return x.view(N, -1)  # "flatten" the C * H * W values into a single vector per image

def test_flatten():
    x = torch.arange(12).view(2, 1, 3, 2)
    print('Before flattening: ', x)
    print('After flattening: ', flatten(x))

test_flatten()

Before flattening:  tensor([[[[ 0,  1],
          [ 2,  3],
          [ 4,  5]]],


        [[[ 6,  7],
          [ 8,  9],
          [10, 11]]]])
After flattening:  tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


### Barebones PyTorch: Two-Layer Network

Here we define a function `two_layer_fc` which performs the forward pass of a two-layer fully-connected ReLU network on a batch of image data. After defining the forward pass we check that it doesn't crash and that it produces outputs of the right shape by running zeros through the network.

You don't have to write any code here, but it's important that you read and understand the implementation.

In [5]:
import torch.nn.functional as F  # useful stateless functions

def two_layer_fc(x, params):
    """
    A fully-connected neural networks; the architecture is:
    NN is fully connected -> ReLU -> fully connected layer.
    Note that this function only defines the forward pass;
    PyTorch will take care of the backward pass for us.

    The input to the network will be a minibatch of data, of shape
    (N, d1, ..., dM) where d1 * ... * dM = D. The hidden layer will have H units,
    and the output layer will produce scores for C classes.

    Inputs:
    - x: A PyTorch Tensor of shape (N, d1, ..., dM) giving a minibatch of
      input data.
    - params: A list [w1, w2] of PyTorch Tensors giving weights for the network;
      w1 has shape (D, H) and w2 has shape (H, C).

    Returns:
    - scores: A PyTorch Tensor of shape (N, C) giving classification scores for
      the input data x.
    """
    # first we flatten the image
    x = flatten(x)  # shape: [batch_size, C x H x W]

    w1, w2 = params

    # Forward pass: compute predicted y using operations on Tensors. Since w1 and
    # w2 have requires_grad=True, operations involving these Tensors will cause
    # PyTorch to build a computational graph, allowing automatic computation of
    # gradients. Since we are no longer implementing the backward pass by hand we
    # don't need to keep references to intermediate values.
    # you can also use `.clamp(min=0)`, equivalent to F.relu()
    x = F.relu(x.mm(w1))
    x = x.mm(w2)
    return x


def two_layer_fc_test():
    hidden_layer_size = 42
    x = torch.zeros((64, 50), dtype=dtype)  # minibatch size 64, feature dimension 50
    w1 = torch.zeros((50, hidden_layer_size), dtype=dtype)
    w2 = torch.zeros((hidden_layer_size, 10), dtype=dtype)
    scores = two_layer_fc(x, [w1, w2])
    print(scores.size())  # you should see [64, 10]

two_layer_fc_test()

torch.Size([64, 10])


### Barebones PyTorch: Three-Layer ConvNet

Here you will complete the implementation of the function `three_layer_convnet`, which will perform the forward pass of a three-layer convolutional network. Like above, we can immediately test our implementation by passing zeros through the network. The network should have the following architecture:

1. A convolutional layer (with bias) with `channel_1` filters, each with shape `KW1 x KH1`, and zero-padding of two
2. ReLU nonlinearity
3. A convolutional layer (with bias) with `channel_2` filters, each with shape `KW2 x KH2`, and zero-padding of one
4. ReLU nonlinearity
5. Fully-connected layer with bias, producing scores for C classes.

Note that we have **no softmax activation** here after our fully-connected layer: this is because PyTorch's cross entropy loss performs a softmax activation for you, and by bundling that step in makes computation more efficient.

**HINT**: For convolutions: http://pytorch.org/docs/stable/nn.html#torch.nn.functional.conv2d; pay attention to the shapes of convolutional filters!

In [6]:
def three_layer_convnet(x, params):
    """
    Performs the forward pass of a three-layer convolutional network with the
    architecture defined above.

    Inputs:
    - x: A PyTorch Tensor of shape (N, 3, H, W) giving a minibatch of images
    - params: A list of PyTorch Tensors giving the weights and biases for the
      network; should contain the following:
      - conv_w1: PyTorch Tensor of shape (channel_1, 3, KH1, KW1) giving weights
        for the first convolutional layer
      - conv_b1: PyTorch Tensor of shape (channel_1,) giving biases for the first
        convolutional layer
      - conv_w2: PyTorch Tensor of shape (channel_2, channel_1, KH2, KW2) giving
        weights for the second convolutional layer
      - conv_b2: PyTorch Tensor of shape (channel_2,) giving biases for the second
        convolutional layer
      - fc_w: PyTorch Tensor giving weights for the fully-connected layer. Can you
        figure out what the shape should be?
      - fc_b: PyTorch Tensor giving biases for the fully-connected layer. Can you
        figure out what the shape should be?

    Returns:
    - scores: PyTorch Tensor of shape (N, C) giving classification scores for x
    """
    conv_w1, conv_b1, conv_w2, conv_b2, fc_w, fc_b = params
    scores = None
    ################################################################################
    # TODO: Implement the forward pass for the three-layer ConvNet.                #
    ################################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    N, C, H, W = x.shape
    x = F.conv2d(x, conv_w1, conv_b1, padding=2)
    x = F.relu(x)
    x = F.conv2d(x, conv_w2, conv_b2, padding=1)
    x = F.relu(x)
    x = flatten(x)
    scores = x.mm(fc_w) + fc_b


    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    ################################################################################
    #                                 END OF YOUR CODE                             #
    ################################################################################
    return scores

After defining the forward pass of the ConvNet above, run the following cell to test your implementation.

When you run this function, scores should have shape (64, 10).

In [7]:
def three_layer_convnet_test():
    x = torch.zeros((64, 3, 32, 32), dtype=dtype)  # minibatch size 64, image size [3, 32, 32]

    conv_w1 = torch.zeros((6, 3, 5, 5), dtype=dtype)  # [out_channel, in_channel, kernel_H, kernel_W]
    conv_b1 = torch.zeros((6,))  # out_channel
    conv_w2 = torch.zeros((9, 6, 3, 3), dtype=dtype)  # [out_channel, in_channel, kernel_H, kernel_W]
    conv_b2 = torch.zeros((9,))  # out_channel

    # you must calculate the shape of the tensor after two conv layers, before the fully-connected layer
    fc_w = torch.zeros((9 * 32 * 32, 10))
    fc_b = torch.zeros(10)

    scores = three_layer_convnet(x, [conv_w1, conv_b1, conv_w2, conv_b2, fc_w, fc_b])
    print(scores.size())  # you should see [64, 10]
three_layer_convnet_test()

torch.Size([64, 10])


### Barebones PyTorch: Initialization
Let's write a couple utility methods to initialize the weight matrices for our models.

- `random_weight(shape)` initializes a weight tensor with the Kaiming normalization method.
- `zero_weight(shape)` initializes a weight tensor with all zeros. Useful for instantiating bias parameters.

The `random_weight` function uses the Kaiming normal initialization method, described in:

He et al, *Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification*, ICCV 2015, https://arxiv.org/abs/1502.01852

In [8]:
def random_weight(shape):
    """
    Create random Tensors for weights; setting requires_grad=True means that we
    want to compute gradients for these Tensors during the backward pass.
    We use Kaiming normalization: sqrt(2 / fan_in)
    """
    if len(shape) == 2:  # FC weight
        fan_in = shape[0]
    else:
        fan_in = np.prod(shape[1:]) # conv weight [out_channel, in_channel, kH, kW]
    # randn is standard normal distribution generator.
    w = torch.randn(shape, device=device, dtype=dtype) * np.sqrt(2. / fan_in)
    w.requires_grad = True
    return w

def zero_weight(shape):
    return torch.zeros(shape, device=device, dtype=dtype, requires_grad=True)

# create a weight of shape [3 x 5]
# you should see the type `torch.cuda.FloatTensor` if you use GPU.
# Otherwise it should be `torch.FloatTensor`
random_weight((3, 5))

tensor([[-0.3930,  0.1982,  0.1362,  0.2029, -0.9096],
        [-1.0298, -0.2643,  0.1737, -0.1450, -0.2457],
        [-0.7546,  0.3793,  0.0566, -0.8423, -0.0061]], device='cuda:0',
       requires_grad=True)

### Barebones PyTorch: Check Accuracy
When training the model we will use the following function to check the accuracy of our model on the training or validation sets.

When checking accuracy we don't need to compute any gradients; as a result we don't need PyTorch to build a computational graph for us when we compute scores. To prevent a graph from being built we scope our computation under a `torch.no_grad()` context manager.

In [9]:
def check_accuracy_part2(loader, model_fn, params):
    """
    Check the accuracy of a classification model.

    Inputs:
    - loader: A DataLoader for the data split we want to check
    - model_fn: A function that performs the forward pass of the model,
      with the signature scores = model_fn(x, params)
    - params: List of PyTorch Tensors giving parameters of the model

    Returns: Nothing, but prints the accuracy of the model
    """
    split = 'val' if loader.dataset.train else 'test'
    print('Checking accuracy on the %s set' % split)
    num_correct, num_samples = 0, 0
    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device, dtype=dtype)  # move to device, e.g. GPU
            y = y.to(device=device, dtype=torch.int64)
            scores = model_fn(x, params)
            _, preds = scores.max(1)
            num_correct += (preds == y).sum()
            num_samples += preds.size(0)
        acc = float(num_correct) / num_samples
        print('Got %d / %d correct (%.2f%%)' % (num_correct, num_samples, 100 * acc))

### BareBones PyTorch: Training Loop
We can now set up a basic training loop to train our network. We will train the model using stochastic gradient descent without momentum. We will use `torch.functional.cross_entropy` to compute the loss; you can [read about it here](http://pytorch.org/docs/stable/nn.html#cross-entropy).

The training loop takes as input the neural network function, a list of initialized parameters (`[w1, w2]` in our example), and learning rate.

In [10]:
def train_part2(model_fn, params, learning_rate):
    """
    Train a model on CIFAR-10.

    Inputs:
    - model_fn: A Python function that performs the forward pass of the model.
      It should have the signature scores = model_fn(x, params) where x is a
      PyTorch Tensor of image data, params is a list of PyTorch Tensors giving
      model weights, and scores is a PyTorch Tensor of shape (N, C) giving
      scores for the elements in x.
    - params: List of PyTorch Tensors giving weights for the model
    - learning_rate: Python scalar giving the learning rate to use for SGD

    Returns: Nothing
    """
    for t, (x, y) in enumerate(loader_train):
        # Move the data to the proper device (GPU or CPU)
        x = x.to(device=device, dtype=dtype)
        y = y.to(device=device, dtype=torch.long)

        # Forward pass: compute scores and loss
        scores = model_fn(x, params)
        loss = F.cross_entropy(scores, y)

        # Backward pass: PyTorch figures out which Tensors in the computational
        # graph has requires_grad=True and uses backpropagation to compute the
        # gradient of the loss with respect to these Tensors, and stores the
        # gradients in the .grad attribute of each Tensor.
        loss.backward()

        # Update parameters. We don't want to backpropagate through the
        # parameter updates, so we scope the updates under a torch.no_grad()
        # context manager to prevent a computational graph from being built.
        with torch.no_grad():
            for w in params:
                w -= learning_rate * w.grad

                # Manually zero the gradients after running the backward pass
                w.grad.zero_()

        if t % print_every == 0:
            print('Iteration %d, loss = %.4f' % (t, loss.item()))
            check_accuracy_part2(loader_val, model_fn, params)
            print()

### BareBones PyTorch: Train a Two-Layer Network
Now we are ready to run the training loop. We need to explicitly allocate tensors for the fully connected weights, `w1` and `w2`.

Each minibatch of CIFAR has 64 examples, so the tensor shape is `[64, 3, 32, 32]`.

After flattening, `x` shape should be `[64, 3 * 32 * 32]`. This will be the size of the first dimension of `w1`.
The second dimension of `w1` is the hidden layer size, which will also be the first dimension of `w2`.

Finally, the output of the network is a 10-dimensional vector that represents the probability distribution over 10 classes.

You don't need to tune any hyperparameters but you should see accuracies above 40% after training for one epoch.

In [11]:
hidden_layer_size = 4000
learning_rate = 1e-2

w1 = random_weight((3 * 32 * 32, hidden_layer_size))
w2 = random_weight((hidden_layer_size, 10))

train_part2(two_layer_fc, [w1, w2], learning_rate)

Iteration 0, loss = 3.7580
Checking accuracy on the val set
Got 116 / 1000 correct (11.60%)

Iteration 100, loss = 2.0543
Checking accuracy on the val set
Got 348 / 1000 correct (34.80%)

Iteration 200, loss = 2.5260
Checking accuracy on the val set
Got 336 / 1000 correct (33.60%)

Iteration 300, loss = 2.4552
Checking accuracy on the val set
Got 414 / 1000 correct (41.40%)

Iteration 400, loss = 1.6451
Checking accuracy on the val set
Got 388 / 1000 correct (38.80%)

Iteration 500, loss = 2.5540
Checking accuracy on the val set
Got 418 / 1000 correct (41.80%)

Iteration 600, loss = 1.5404
Checking accuracy on the val set
Got 437 / 1000 correct (43.70%)

Iteration 700, loss = 1.6798
Checking accuracy on the val set
Got 479 / 1000 correct (47.90%)



### BareBones PyTorch: Training a ConvNet

In the below you should use the functions defined above to train a three-layer convolutional network on CIFAR. The network should have the following architecture:

1. Convolutional layer (with bias) with 32 5x5 filters, with zero-padding of 2
2. ReLU
3. Convolutional layer (with bias) with 16 3x3 filters, with zero-padding of 1
4. ReLU
5. Fully-connected layer (with bias) to compute scores for 10 classes

You should initialize your weight matrices using the `random_weight` function defined above, and you should initialize your bias vectors using the `zero_weight` function above.

You don't need to tune any hyperparameters, but if everything works correctly you should achieve an accuracy above 42% after one epoch.

In [12]:
learning_rate = 3e-3

channel_1 = 32
channel_2 = 16

conv_w1 = None
conv_b1 = None
conv_w2 = None
conv_b2 = None
fc_w = None
fc_b = None

################################################################################
# TODO: Initialize the parameters of a three-layer ConvNet.                    #
################################################################################
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

print(loader_train)
conv_w1 = random_weight((channel_1, 3, 5, 5))
conv_b1 = zero_weight((channel_1, ))
conv_w2 = random_weight((channel_2, channel_1, 3, 3))
conv_b2 = zero_weight((channel_2, ))
fc_w = random_weight((channel_2 * 32 * 32, 10))
fc_b = zero_weight((10, ))

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

params = [conv_w1, conv_b1, conv_w2, conv_b2, fc_w, fc_b]
train_part2(three_layer_convnet, params, learning_rate)

Iteration 0, loss = 3.4753
Checking accuracy on the val set
Got 94 / 1000 correct (9.40%)

Iteration 100, loss = 1.9887
Checking accuracy on the val set
Got 350 / 1000 correct (35.00%)

Iteration 200, loss = 1.8277
Checking accuracy on the val set
Got 391 / 1000 correct (39.10%)

Iteration 300, loss = 1.5893
Checking accuracy on the val set
Got 421 / 1000 correct (42.10%)

Iteration 400, loss = 1.4963
Checking accuracy on the val set
Got 448 / 1000 correct (44.80%)

Iteration 500, loss = 1.5308
Checking accuracy on the val set
Got 453 / 1000 correct (45.30%)

Iteration 600, loss = 1.8567
Checking accuracy on the val set
Got 472 / 1000 correct (47.20%)

Iteration 700, loss = 1.6165
Checking accuracy on the val set
Got 483 / 1000 correct (48.30%)



# Part III. PyTorch Module API

Barebone PyTorch requires that we track all the parameter tensors by hand. This is fine for small networks with a few tensors, but it would be extremely inconvenient and error-prone to track tens or hundreds of tensors in larger networks.

PyTorch provides the `nn.Module` API for you to define arbitrary network architectures, while tracking every learnable parameters for you. In Part II, we implemented SGD ourselves. PyTorch also provides the `torch.optim` package that implements all the common optimizers, such as RMSProp, Adagrad, and Adam. It even supports approximate second-order methods like L-BFGS! You can refer to the [doc](http://pytorch.org/docs/master/optim.html) for the exact specifications of each optimizer.

To use the Module API, follow the steps below:

1. Subclass `nn.Module`. Give your network class an intuitive name like `TwoLayerFC`.

2. In the constructor `__init__()`, define all the layers you need as class attributes. Layer objects like `nn.Linear` and `nn.Conv2d` are themselves `nn.Module` subclasses and contain learnable parameters, so that you don't have to instantiate the raw tensors yourself. `nn.Module` will track these internal parameters for you. Refer to the [doc](http://pytorch.org/docs/master/nn.html) to learn more about the dozens of builtin layers. **Warning**: don't forget to call the `super().__init__()` first!

3. In the `forward()` method, define the *connectivity* of your network. You should use the attributes defined in `__init__` as function calls that take tensor as input and output the "transformed" tensor. Do *not* create any new layers with learnable parameters in `forward()`! All of them must be declared upfront in `__init__`.

After you define your Module subclass, you can instantiate it as an object and call it just like the NN forward function in part II.

### Module API: Two-Layer Network
Here is a concrete example of a 2-layer fully connected network:

In [13]:
class TwoLayerFC(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        # assign layer objects to class attributes
        self.fc1 = nn.Linear(input_size, hidden_size)
        # nn.init package contains convenient initialization methods
        # http://pytorch.org/docs/master/nn.html#torch-nn-init
        nn.init.kaiming_normal_(self.fc1.weight)
        self.fc2 = nn.Linear(hidden_size, num_classes)
        nn.init.kaiming_normal_(self.fc2.weight)

    def forward(self, x):
        # forward always defines connectivity
        x = flatten(x)
        scores = self.fc2(F.relu(self.fc1(x)))
        return scores

def test_TwoLayerFC():
    input_size = 50
    x = torch.zeros((64, input_size), dtype=dtype)  # minibatch size 64, feature dimension 50
    model = TwoLayerFC(input_size, 42, 10)
    scores = model(x)
    print(scores.size())  # you should see [64, 10]
test_TwoLayerFC()

torch.Size([64, 10])


### Module API: Three-Layer ConvNet
It's your turn to implement a 3-layer ConvNet followed by a fully connected layer. The network architecture should be the same as in Part II:

1. Convolutional layer with `channel_1` 5x5 filters with zero-padding of 2
2. ReLU
3. Convolutional layer with `channel_2` 3x3 filters with zero-padding of 1
4. ReLU
5. Fully-connected layer to `num_classes` classes

You should initialize the weight matrices of the model using the Kaiming normal initialization method.

**HINT**: http://pytorch.org/docs/stable/nn.html#conv2d

After you implement the three-layer ConvNet, the `test_ThreeLayerConvNet` function will run your implementation; it should print `(64, 10)` for the shape of the output scores.

In [14]:
class ThreeLayerConvNet(nn.Module):
    def __init__(self, in_channel, channel_1, channel_2, num_classes):
        super().__init__()
        ########################################################################
        # TODO: Set up the layers you need for a three-layer ConvNet with the  #
        # architecture defined above.                                          #
        ########################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

        self.l1 = nn.Conv2d(in_channel, channel_1, 5, padding=2)
        nn.init.kaiming_normal_(self.l1.weight)
        self.l2 = nn.Conv2d(channel_1, channel_2, 3, padding=1)
        nn.init.kaiming_normal_(self.l1.weight)
        self.l3 = nn.Linear(channel_2 * 32 * 32, num_classes)

        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        ########################################################################
        #                          END OF YOUR CODE                            #
        ########################################################################

    def forward(self, x):
        scores = None
        ########################################################################
        # TODO: Implement the forward function for a 3-layer ConvNet. you      #
        # should use the layers you defined in __init__ and specify the        #
        # connectivity of those layers in forward()                            #
        ########################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

        x = F.relu(self.l1(x))
        x = F.relu(self.l2(x))
        x = flatten(x)
        scores = self.l3(x)

        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        ########################################################################
        #                             END OF YOUR CODE                         #
        ########################################################################
        return scores


def test_ThreeLayerConvNet():
    x = torch.zeros((64, 3, 32, 32), dtype=dtype)  # minibatch size 64, image size [3, 32, 32]
    model = ThreeLayerConvNet(in_channel=3, channel_1=12, channel_2=8, num_classes=10)
    scores = model(x)
    print(scores.size())  # you should see [64, 10]
test_ThreeLayerConvNet()

torch.Size([64, 10])


### Module API: Check Accuracy
Given the validation or test set, we can check the classification accuracy of a neural network.

This version is slightly different from the one in part II. You don't manually pass in the parameters anymore.

In [15]:
def check_accuracy_part34(loader, model):
    if loader.dataset.train:
        print('Checking accuracy on validation set')
    else:
        print('Checking accuracy on test set')
    num_correct = 0
    num_samples = 0
    model.eval()  # set model to evaluation mode
    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device, dtype=dtype)  # move to device, e.g. GPU
            y = y.to(device=device, dtype=torch.long)
            scores = model(x)
            _, preds = scores.max(1)
            num_correct += (preds == y).sum()
            num_samples += preds.size(0)
        acc = float(num_correct) / num_samples
        print('Got %d / %d correct (%.2f)' % (num_correct, num_samples, 100 * acc))

### Module API: Training Loop
We also use a slightly different training loop. Rather than updating the values of the weights ourselves, we use an Optimizer object from the `torch.optim` package, which abstract the notion of an optimization algorithm and provides implementations of most of the algorithms commonly used to optimize neural networks.

In [16]:
def train_part34(model, optimizer, epochs=1):
    """
    Train a model on CIFAR-10 using the PyTorch Module API.

    Inputs:
    - model: A PyTorch Module giving the model to train.
    - optimizer: An Optimizer object we will use to train the model
    - epochs: (Optional) A Python integer giving the number of epochs to train for

    Returns: Nothing, but prints model accuracies during training.
    """
    model = model.to(device=device)  # move the model parameters to CPU/GPU
    for e in range(epochs):
        for t, (x, y) in enumerate(loader_train):
            model.train()  # put model to training mode
            x = x.to(device=device, dtype=dtype)  # move to device, e.g. GPU
            y = y.to(device=device, dtype=torch.long)

            scores = model(x)
            loss = F.cross_entropy(scores, y)

            # Zero out all of the gradients for the variables which the optimizer
            # will update.
            optimizer.zero_grad()

            # This is the backwards pass: compute the gradient of the loss with
            # respect to each  parameter of the model.
            loss.backward()

            # Actually update the parameters of the model using the gradients
            # computed by the backwards pass.
            optimizer.step()

            if t % print_every == 0:
                print('Iteration %d, loss = %.4f' % (t, loss.item()))
                check_accuracy_part34(loader_val, model)
                print()

### Module API: Train a Two-Layer Network
Now we are ready to run the training loop. In contrast to part II, we don't explicitly allocate parameter tensors anymore.

Simply pass the input size, hidden layer size, and number of classes (i.e. output size) to the constructor of `TwoLayerFC`.

You also need to define an optimizer that tracks all the learnable parameters inside `TwoLayerFC`.

You don't need to tune any hyperparameters, but you should see model accuracies above 40% after training for one epoch.

In [17]:
hidden_layer_size = 4000
learning_rate = 1e-2
model = TwoLayerFC(3 * 32 * 32, hidden_layer_size, 10)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

train_part34(model, optimizer)

Iteration 0, loss = 3.0597
Checking accuracy on validation set
Got 171 / 1000 correct (17.10)

Iteration 100, loss = 1.8825
Checking accuracy on validation set
Got 380 / 1000 correct (38.00)

Iteration 200, loss = 2.4227
Checking accuracy on validation set
Got 331 / 1000 correct (33.10)

Iteration 300, loss = 2.2266
Checking accuracy on validation set
Got 374 / 1000 correct (37.40)

Iteration 400, loss = 1.5837
Checking accuracy on validation set
Got 426 / 1000 correct (42.60)

Iteration 500, loss = 1.9937
Checking accuracy on validation set
Got 390 / 1000 correct (39.00)

Iteration 600, loss = 1.7206
Checking accuracy on validation set
Got 405 / 1000 correct (40.50)

Iteration 700, loss = 1.6967
Checking accuracy on validation set
Got 436 / 1000 correct (43.60)



### Module API: Train a Three-Layer ConvNet
You should now use the Module API to train a three-layer ConvNet on CIFAR. This should look very similar to training the two-layer network! You don't need to tune any hyperparameters, but you should achieve above above 45% after training for one epoch.

You should train the model using stochastic gradient descent without momentum.

In [18]:
learning_rate = 3e-3
channel_1 = 32
channel_2 = 16

model = None
optimizer = None
################################################################################
# TODO: Instantiate your ThreeLayerConvNet model and a corresponding optimizer #
################################################################################
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

model = ThreeLayerConvNet(3, channel_1, channel_2, 10)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

train_part34(model, optimizer)

Iteration 0, loss = 2.3554
Checking accuracy on validation set
Got 126 / 1000 correct (12.60)

Iteration 100, loss = 1.8660
Checking accuracy on validation set
Got 350 / 1000 correct (35.00)

Iteration 200, loss = 1.7895
Checking accuracy on validation set
Got 407 / 1000 correct (40.70)

Iteration 300, loss = 1.4947
Checking accuracy on validation set
Got 425 / 1000 correct (42.50)

Iteration 400, loss = 1.6902
Checking accuracy on validation set
Got 454 / 1000 correct (45.40)

Iteration 500, loss = 1.4524
Checking accuracy on validation set
Got 452 / 1000 correct (45.20)

Iteration 600, loss = 1.7071
Checking accuracy on validation set
Got 466 / 1000 correct (46.60)

Iteration 700, loss = 1.4723
Checking accuracy on validation set
Got 478 / 1000 correct (47.80)



# Part IV. PyTorch Sequential API

Part III introduced the PyTorch Module API, which allows you to define arbitrary learnable layers and their connectivity.

For simple models like a stack of feed forward layers, you still need to go through 3 steps: subclass `nn.Module`, assign layers to class attributes in `__init__`, and call each layer one by one in `forward()`. Is there a more convenient way?

Fortunately, PyTorch provides a container Module called `nn.Sequential`, which merges the above steps into one. It is not as flexible as `nn.Module`, because you cannot specify more complex topology than a feed-forward stack, but it's good enough for many use cases.

### Sequential API: Two-Layer Network
Let's see how to rewrite our two-layer fully connected network example with `nn.Sequential`, and train it using the training loop defined above.

Again, you don't need to tune any hyperparameters here, but you shoud achieve above 40% accuracy after one epoch of training.

In [19]:
# We need to wrap `flatten` function in a module in order to stack it
# in nn.Sequential
class Flatten(nn.Module):
    def forward(self, x):
        return flatten(x)

hidden_layer_size = 4000
learning_rate = 1e-2

model = nn.Sequential(
    Flatten(),
    nn.Linear(3 * 32 * 32, hidden_layer_size),
    nn.ReLU(),
    nn.Linear(hidden_layer_size, 10),
)

# you can use Nesterov momentum in optim.SGD
optimizer = optim.SGD(model.parameters(), lr=learning_rate,
                     momentum=0.9, nesterov=True)

train_part34(model, optimizer)

Iteration 0, loss = 2.3153
Checking accuracy on validation set
Got 155 / 1000 correct (15.50)

Iteration 100, loss = 1.8437
Checking accuracy on validation set
Got 404 / 1000 correct (40.40)

Iteration 200, loss = 1.7596
Checking accuracy on validation set
Got 408 / 1000 correct (40.80)

Iteration 300, loss = 1.6165
Checking accuracy on validation set
Got 420 / 1000 correct (42.00)

Iteration 400, loss = 2.1283
Checking accuracy on validation set
Got 399 / 1000 correct (39.90)

Iteration 500, loss = 1.7525
Checking accuracy on validation set
Got 449 / 1000 correct (44.90)

Iteration 600, loss = 1.7289
Checking accuracy on validation set
Got 441 / 1000 correct (44.10)

Iteration 700, loss = 1.7704
Checking accuracy on validation set
Got 438 / 1000 correct (43.80)



### Sequential API: Three-Layer ConvNet
Here you should use `nn.Sequential` to define and train a three-layer ConvNet with the same architecture we used in Part III:

1. Convolutional layer (with bias) with 32 5x5 filters, with zero-padding of 2
2. ReLU
3. Convolutional layer (with bias) with 16 3x3 filters, with zero-padding of 1
4. ReLU
5. Fully-connected layer (with bias) to compute scores for 10 classes

You can use the default PyTorch weight initialization.

You should optimize your model using stochastic gradient descent with Nesterov momentum 0.9.

Again, you don't need to tune any hyperparameters but you should see accuracy above 55% after one epoch of training.

In [22]:
channel_1 = 32
channel_2 = 16
learning_rate = 1e-2

model = None
optimizer = None

################################################################################
# TODO: Rewrite the 3-layer ConvNet with bias from Part III with the           #
# Sequential API.                                                              #
################################################################################
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

model = nn.Sequential(
    ThreeLayerConvNet(3, channel_1, channel_2, 10)
)

optimizer = optim.SGD(model.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

train_part34(model, optimizer)

Iteration 0, loss = 2.2869
Checking accuracy on validation set
Got 150 / 1000 correct (15.00)

Iteration 100, loss = 1.5640
Checking accuracy on validation set
Got 368 / 1000 correct (36.80)

Iteration 200, loss = 1.4234
Checking accuracy on validation set
Got 448 / 1000 correct (44.80)

Iteration 300, loss = 1.3772
Checking accuracy on validation set
Got 499 / 1000 correct (49.90)

Iteration 400, loss = 1.3244
Checking accuracy on validation set
Got 559 / 1000 correct (55.90)

Iteration 500, loss = 1.3325
Checking accuracy on validation set
Got 546 / 1000 correct (54.60)

Iteration 600, loss = 1.3008
Checking accuracy on validation set
Got 566 / 1000 correct (56.60)

Iteration 700, loss = 1.0365
Checking accuracy on validation set
Got 579 / 1000 correct (57.90)



# Part V. CIFAR-10 open-ended challenge

In this section, you can experiment with whatever ConvNet architecture you'd like on CIFAR-10.

Now it's your job to experiment with architectures, hyperparameters, loss functions, and optimizers to train a model that achieves **at least 70%** accuracy on the CIFAR-10 **validation** set within 10 epochs. You can use the check_accuracy and train functions from above. You can use either `nn.Module` or `nn.Sequential` API.

Describe what you did at the end of this notebook.

Here are the official API documentation for each component. One note: what we call in the class "spatial batch norm" is called "BatchNorm2D" in PyTorch.

* Layers in torch.nn package: http://pytorch.org/docs/stable/nn.html
* Activations: http://pytorch.org/docs/stable/nn.html#non-linear-activations
* Loss functions: http://pytorch.org/docs/stable/nn.html#loss-functions
* Optimizers: http://pytorch.org/docs/stable/optim.html


### Things you might try:
- **Filter size**: Above we used 5x5; would smaller filters be more efficient?
- **Number of filters**: Above we used 32 filters. Do more or fewer do better?
- **Pooling vs Strided Convolution**: Do you use max pooling or just stride convolutions?
- **Batch normalization**: Try adding spatial batch normalization after convolution layers and vanilla batch normalization after affine layers. Do your networks train faster?
- **Network architecture**: The network above has two layers of trainable parameters. Can you do better with a deep network? Good architectures to try include:
    - [conv-relu-pool]xN -> [affine]xM -> [softmax or SVM]
    - [conv-relu-conv-relu-pool]xN -> [affine]xM -> [softmax or SVM]
    - [batchnorm-relu-conv]xN -> [affine]xM -> [softmax or SVM]
- **Global Average Pooling**: Instead of flattening and then having multiple affine layers, perform convolutions until your image gets small (7x7 or so) and then perform an average pooling operation to get to a 1x1 image picture (1, 1 , Filter#), which is then reshaped into a (Filter#) vector. This is used in [Google's Inception Network](https://arxiv.org/abs/1512.00567) (See Table 1 for their architecture).
- **Regularization**: Add l2 weight regularization, or perhaps use Dropout.

### Tips for training
For each network architecture that you try, you should tune the learning rate and other hyperparameters. When doing this there are a couple important things to keep in mind:

- If the parameters are working well, you should see improvement within a few hundred iterations
- Remember the coarse-to-fine approach for hyperparameter tuning: start by testing a large range of hyperparameters for just a few training iterations to find the combinations of parameters that are working at all.
- Once you have found some sets of parameters that seem to work, search more finely around these parameters. You may need to train for more epochs.
- You should use the validation set for hyperparameter search, and save your test set for evaluating your architecture on the best parameters as selected by the validation set.

### Going above and beyond
If you are feeling adventurous there are many other features you can implement to try and improve your performance. You are **not required** to implement any of these, but don't miss the fun if you have time!

- Alternative optimizers: you can try Adam, Adagrad, RMSprop, etc.
- Alternative activation functions such as leaky ReLU, parametric ReLU, ELU, or MaxOut.
- Model ensembles
- Data augmentation
- New Architectures
  - [ResNets](https://arxiv.org/abs/1512.03385) where the input from the previous layer is added to the output.
  - [DenseNets](https://arxiv.org/abs/1608.06993) where inputs into previous layers are concatenated together.
  - [This blog has an in-depth overview](https://chatbotslife.com/resnets-highwaynets-and-densenets-oh-my-9bb15918ee32)

### Have fun and happy training!

 ## 🎯 Step 1: 기본 모델 구조 설정
 - cs231n 강의에서 배운 **Residual Learning** idea를 적용.
 - [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 선택.
 - N = 3, M = 1 시도.
 - kernel size = 3, stride=1, padding = 1 으로 설정. (원본 사이즈 유지)
 - 중간 channels의 수 = 64로 고정.
 - learning_rate = 1e-3, epoch = 10
 - 최종 val_acc = 67.5%




In [23]:
# Residual Block 클래스 선언

class ResBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()

        self.residual = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3,
                      stride=stride, padding=1, bias=False),
            nn.ReLU(),
            nn.Conv2d(out_channels, out_channels, kernel_size=3,
                      stride=1, padding=1, bias=False)
        )

        self.identity = nn.Identity()
        # 입출력의 사이즈가 다를 때 identity function을 따로 지정.
        if (stride != 1 or in_channels != out_channels):
            self.identity = nn.Conv2d(in_channels, out_channels, kernel_size=1,
                          stride=stride, bias=False)

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.residual(x) + self.identity(x)
        scores = self.relu(x)
        return scores


In [24]:
## 에폭당 한 번만 진행상황을 출력하는 train 함수 선언.
## (train_part34 이용)
def train_part5(model, optimizer, epochs=1, print_per_epoch=False):
    """
    Train a model on CIFAR-10 using the PyTorch Module API.

    Inputs:
    - model: A PyTorch Module giving the model to train.
    - optimizer: An Optimizer object we will use to train the model
    - epochs: (Optional) A Python integer giving the number of epochs to train for

    Returns: Nothing, but prints model accuracies during training.
    """
    model = model.to(device=device)  # move the model parameters to CPU/GPU
    for e in range(epochs):
        for t, (x, y) in enumerate(loader_train):
            model.train()  # put model to training mode
            x = x.to(device=device, dtype=dtype)  # move to device, e.g. GPU
            y = y.to(device=device, dtype=torch.long)

            scores = model(x)
            loss = F.cross_entropy(scores, y)

            # Zero out all of the gradients for the variables which the optimizer
            # will update.
            optimizer.zero_grad()

            # This is the backwards pass: compute the gradient of the loss with
            # respect to each  parameter of the model.
            loss.backward()

            # Actually update the parameters of the model using the gradients
            # computed by the backwards pass.
            optimizer.step()

            if print_per_epoch == False:
                print('Iteration %d, loss = %.4f' % (t, loss.item()))
                check_accuracy_part34(loader_val, model)
                print()

        if print_per_epoch == True:
            print('epoch %d, loss = %.4f' % (e+1, loss.item()))
            check_accuracy_part34(loader_val, model)
            print()

In [71]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model1 = None
optimizer1 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3


model1 = nn.Sequential(
    ResBlock(in_channels, 64, stride=1),
    ResBlock(64, 64, stride=1),
    ResBlock(64, 64, stride=1),
    nn.Flatten(),
    nn.Linear(64 * 32 * 32, 10)
)

optimizer1 = optim.SGD(model1.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model1, optimizer1, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.3579
Checking accuracy on validation set
Got 542 / 1000 correct (54.20)

epoch 2, loss = 1.3860
Checking accuracy on validation set
Got 596 / 1000 correct (59.60)

epoch 3, loss = 1.2913
Checking accuracy on validation set
Got 632 / 1000 correct (63.20)

epoch 4, loss = 0.7800
Checking accuracy on validation set
Got 651 / 1000 correct (65.10)

epoch 5, loss = 0.6321
Checking accuracy on validation set
Got 663 / 1000 correct (66.30)

epoch 6, loss = 0.6719
Checking accuracy on validation set
Got 682 / 1000 correct (68.20)

epoch 7, loss = 0.6230
Checking accuracy on validation set
Got 662 / 1000 correct (66.20)

epoch 8, loss = 0.5869
Checking accuracy on validation set
Got 663 / 1000 correct (66.30)

epoch 9, loss = 0.4644
Checking accuracy on validation set
Got 661 / 1000 correct (66.10)

epoch 10, loss = 0.4182
Checking accuracy on validation set
Got 675 / 1000 correct (67.50)



---

 ## 🎯 Step 2: BatchNorm 추가

- Residual Block에 **BatchNorm 추가**, 나머지 조건 유지.
- [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 유지.
- N = 3, M = 1 유지.
- kernel size = 3, stride=1, padding = 1 으로 설정. (원본 사이즈 유지)
- 중간 channels의 수 = 64로 고정.
- learning_rate = 1e-3, epoch = 10


- **실험 결과**
 - 최종 val_acc = 69.2%
 - BatchNorm 적용 전보다 val_acc 상승 (67.5% → 69.2%)





In [25]:
# Residual with batchnorm 클래스 선언

class ResBlockBn(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()

        self.residual = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3,
                      stride=stride, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(),
            nn.Conv2d(out_channels, out_channels, kernel_size=3,
                      stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels)
        )

        self.identity = nn.Identity()
        # 입출력의 사이즈가 다를 때 identity function을 따로 지정.
        if (stride != 1 or in_channels != out_channels):
            self.identity = nn.Conv2d(in_channels, out_channels, kernel_size=1,
                          stride=stride, bias=False)
            nn.BatchNorm2d(out_channels)

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.residual(x) + self.identity(x)
        scores = self.relu(x)
        return scores


In [81]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model2 = None
optimizer2 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3


model2 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    nn.Flatten(),
    nn.Linear(64 * 32 * 32, 10)
)

optimizer2 = optim.SGD(model2.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model2, optimizer2, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.2673
Checking accuracy on validation set
Got 547 / 1000 correct (54.70)

epoch 2, loss = 1.0287
Checking accuracy on validation set
Got 626 / 1000 correct (62.60)

epoch 3, loss = 0.9038
Checking accuracy on validation set
Got 656 / 1000 correct (65.60)

epoch 4, loss = 0.7773
Checking accuracy on validation set
Got 652 / 1000 correct (65.20)

epoch 5, loss = 0.4456
Checking accuracy on validation set
Got 679 / 1000 correct (67.90)

epoch 6, loss = 0.4279
Checking accuracy on validation set
Got 691 / 1000 correct (69.10)

epoch 7, loss = 0.2605
Checking accuracy on validation set
Got 679 / 1000 correct (67.90)

epoch 8, loss = 0.3418
Checking accuracy on validation set
Got 670 / 1000 correct (67.00)

epoch 9, loss = 0.4232
Checking accuracy on validation set
Got 693 / 1000 correct (69.30)

epoch 10, loss = 0.3551
Checking accuracy on validation set
Got 692 / 1000 correct (69.20)



 ## 🎯 Step 3: 모델 깊이 조정

- Residual Block 개수(N) 증가, 나머지 조건 유지.
- [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 유지.
- M = 1 유지.
- N = 5, 7 설정.
- kernel size = 3, stride=1, padding = 1 으로 설정. (원본 사이즈 유지)
- 중간 channels의 수 = 64로 고정.
- learning_rate = 1e-3, epoch = 10


- **실험 결과**
 - (N = 3) val_acc = 69.2%
 - (N = 5) val_acc = 70.0%
 - (N = 7) val_acc = 69.4%
 - N = 3일 때와 비교해서 유의미한 성능 차이 없음.
 - 단순히 Residual Block을 깊게 쌓는 것만으로는 성능 향상을 기대하기 어려움.





In [82]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model3 = None
optimizer3 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3

model3 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    nn.Flatten(),
    nn.Linear(64 * 32 * 32, 10)
)

optimizer3 = optim.SGD(model3.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model3, optimizer3, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.2923
Checking accuracy on validation set
Got 575 / 1000 correct (57.50)

epoch 2, loss = 1.2498
Checking accuracy on validation set
Got 623 / 1000 correct (62.30)

epoch 3, loss = 0.7937
Checking accuracy on validation set
Got 650 / 1000 correct (65.00)

epoch 4, loss = 0.7008
Checking accuracy on validation set
Got 671 / 1000 correct (67.10)

epoch 5, loss = 0.5922
Checking accuracy on validation set
Got 696 / 1000 correct (69.60)

epoch 6, loss = 0.4447
Checking accuracy on validation set
Got 668 / 1000 correct (66.80)

epoch 7, loss = 0.3099
Checking accuracy on validation set
Got 697 / 1000 correct (69.70)

epoch 8, loss = 0.2703
Checking accuracy on validation set
Got 696 / 1000 correct (69.60)

epoch 9, loss = 0.4088
Checking accuracy on validation set
Got 698 / 1000 correct (69.80)

epoch 10, loss = 0.3795
Checking accuracy on validation set
Got 700 / 1000 correct (70.00)



In [83]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model3_2 = None
optimizer3_2 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3

model3_2 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    ResBlockBn(64, 64, stride=1),
    nn.Flatten(),
    nn.Linear(64 * 32 * 32, 10)
)

optimizer3_2 = optim.SGD(model3_2.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model3_2, optimizer3_2, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.5886
Checking accuracy on validation set
Got 534 / 1000 correct (53.40)

epoch 2, loss = 0.8377
Checking accuracy on validation set
Got 600 / 1000 correct (60.00)

epoch 3, loss = 0.9177
Checking accuracy on validation set
Got 639 / 1000 correct (63.90)

epoch 4, loss = 0.6792
Checking accuracy on validation set
Got 663 / 1000 correct (66.30)

epoch 5, loss = 0.7333
Checking accuracy on validation set
Got 698 / 1000 correct (69.80)

epoch 6, loss = 0.8781
Checking accuracy on validation set
Got 692 / 1000 correct (69.20)

epoch 7, loss = 0.4388
Checking accuracy on validation set
Got 678 / 1000 correct (67.80)

epoch 8, loss = 0.1913
Checking accuracy on validation set
Got 702 / 1000 correct (70.20)

epoch 9, loss = 0.4963
Checking accuracy on validation set
Got 693 / 1000 correct (69.30)

epoch 10, loss = 0.2888
Checking accuracy on validation set
Got 694 / 1000 correct (69.40)



 ## 🎯 Step 4: channel 및 해상도 조정

- Residual Block을 통과하면서 해상도는 감소하고 channel 수가 증가하도록 설정.
- [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 유지.
- N = 5, M = 1 설정.
- learning_rate = 1e-3, epoch = 10


- **실험 결과**
 - val_acc = **80.7%**
 - val_acc 크게 상승 (69.2% → 80.7%)




In [85]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model4 = None
optimizer4 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3

model4 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 128, stride=2),
    ResBlockBn(128, 128, stride=1),
    ResBlockBn(128, 256, stride=2),
    ResBlockBn(256, 256, stride=1),
    nn.Flatten(),
    nn.Linear(256 * 8 * 8, 10)
)

optimizer4 = optim.SGD(model4.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model4, optimizer4, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.4707
Checking accuracy on validation set
Got 633 / 1000 correct (63.30)

epoch 2, loss = 0.8239
Checking accuracy on validation set
Got 716 / 1000 correct (71.60)

epoch 3, loss = 0.6126
Checking accuracy on validation set
Got 746 / 1000 correct (74.60)

epoch 4, loss = 0.3624
Checking accuracy on validation set
Got 750 / 1000 correct (75.00)

epoch 5, loss = 0.3698
Checking accuracy on validation set
Got 752 / 1000 correct (75.20)

epoch 6, loss = 0.1852
Checking accuracy on validation set
Got 761 / 1000 correct (76.10)

epoch 7, loss = 0.0409
Checking accuracy on validation set
Got 801 / 1000 correct (80.10)

epoch 8, loss = 0.0360
Checking accuracy on validation set
Got 797 / 1000 correct (79.70)

epoch 9, loss = 0.0028
Checking accuracy on validation set
Got 803 / 1000 correct (80.30)

epoch 10, loss = 0.0022
Checking accuracy on validation set
Got 807 / 1000 correct (80.70)



 ## 🎯 Step 5: 모델 깊이 조정

- [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 유지.
- N = 7, M = 1 설정.
- learning_rate = 1e-3, epoch = 10

- **실험 결과**
 - val_acc = **78.9%**
 - val_acc 감소 (80.7% → 78.9%)
 - N = 5로 유지 결정.




In [86]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model5 = None
optimizer5 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3

model5 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 128, stride=2),
    ResBlockBn(128, 128, stride=1),
    ResBlockBn(128, 256, stride=2),
    ResBlockBn(256, 256, stride=1),
    ResBlockBn(256, 512, stride=2),
    ResBlockBn(512, 512, stride=1),
    ResBlockBn(512, 1024, stride=2),
    nn.Flatten(),
    nn.Linear(1024 * 2 * 2, 10)
)

optimizer5 = optim.SGD(model5.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model5, optimizer5, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.1171
Checking accuracy on validation set
Got 630 / 1000 correct (63.00)

epoch 2, loss = 0.9941
Checking accuracy on validation set
Got 731 / 1000 correct (73.10)

epoch 3, loss = 0.5946
Checking accuracy on validation set
Got 769 / 1000 correct (76.90)

epoch 4, loss = 0.3767
Checking accuracy on validation set
Got 751 / 1000 correct (75.10)

epoch 5, loss = 0.3490
Checking accuracy on validation set
Got 739 / 1000 correct (73.90)

epoch 6, loss = 0.1832
Checking accuracy on validation set
Got 746 / 1000 correct (74.60)

epoch 7, loss = 0.1094
Checking accuracy on validation set
Got 730 / 1000 correct (73.00)

epoch 8, loss = 0.0595
Checking accuracy on validation set
Got 771 / 1000 correct (77.10)

epoch 9, loss = 0.1093
Checking accuracy on validation set
Got 773 / 1000 correct (77.30)

epoch 10, loss = 0.0091
Checking accuracy on validation set
Got 789 / 1000 correct (78.90)



 ## 🎯 Step 6: Affine Layer 깊이 조정 + Dropout 적용

- [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 유지.
- N = 5, M = 2설정.
- learning_rate = 1e-3, epoch = 10
- Dropout 적용.


- **실험 결과**
 - val_acc = 80.4%
 - M = 1 일 때 (80.7%) 와 비교해서 유의미한 차이 없음.
 - → overfitting 의심됨.
 - → L2 regularization 추가.



In [27]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model6 = None
optimizer6 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3

model6 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 128, stride=2),
    ResBlockBn(128, 128, stride=1),
    ResBlockBn(128, 256, stride=2),
    ResBlockBn(256, 256, stride=1),
    nn.Flatten(),
    nn.Linear(256 * 8 * 8, 128),
    nn.ReLU(),
    nn.Dropout(p=0.5),
    nn.Linear(128, 10)
)

optimizer6 = optim.SGD(model6.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model6, optimizer6, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.6618
Checking accuracy on validation set
Got 569 / 1000 correct (56.90)

epoch 2, loss = 1.1661
Checking accuracy on validation set
Got 670 / 1000 correct (67.00)

epoch 3, loss = 0.8763
Checking accuracy on validation set
Got 703 / 1000 correct (70.30)

epoch 4, loss = 0.4974
Checking accuracy on validation set
Got 747 / 1000 correct (74.70)

epoch 5, loss = 0.7574
Checking accuracy on validation set
Got 789 / 1000 correct (78.90)

epoch 6, loss = 0.5231
Checking accuracy on validation set
Got 791 / 1000 correct (79.10)

epoch 7, loss = 0.5884
Checking accuracy on validation set
Got 762 / 1000 correct (76.20)

epoch 8, loss = 0.5273
Checking accuracy on validation set
Got 804 / 1000 correct (80.40)

epoch 9, loss = 0.5433
Checking accuracy on validation set
Got 809 / 1000 correct (80.90)

epoch 10, loss = 0.0796
Checking accuracy on validation set
Got 804 / 1000 correct (80.40)



 ## 🎯 Step 7: L2 regularization 적용

- [{(conv -> relu -> conv) + identity} -> relu] * N -> affine * M -> softmax 구조 유지.
- N = 5, M = 2 유지
- learning_rate = 1e-3, epoch = 10
- Dropout + L2 regularization 적용
- reg = 1e-3 설정.


- **실험 결과**
 - val_acc = 83.1%
 - 80.4% → 83.1%로 상승.



In [35]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model7 = None
optimizer7 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 1e-3

model7 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 128, stride=2),
    ResBlockBn(128, 128, stride=1),
    ResBlockBn(128, 256, stride=2),
    ResBlockBn(256, 256, stride=1),
    nn.Flatten(),
    nn.Linear(256 * 8 * 8, 128),
    nn.ReLU(),
    nn.Dropout(p=0.5),
    nn.Linear(128, 10)
)

optimizer7 = optim.SGD(model7.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True, weight_decay=1e-3)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model7, optimizer7, epochs=10, print_per_epoch=True)

epoch 1, loss = 1.3973
Checking accuracy on validation set
Got 578 / 1000 correct (57.80)

epoch 2, loss = 0.9702
Checking accuracy on validation set
Got 673 / 1000 correct (67.30)

epoch 3, loss = 0.6380
Checking accuracy on validation set
Got 716 / 1000 correct (71.60)

epoch 4, loss = 0.6033
Checking accuracy on validation set
Got 712 / 1000 correct (71.20)

epoch 5, loss = 0.7155
Checking accuracy on validation set
Got 776 / 1000 correct (77.60)

epoch 6, loss = 0.7232
Checking accuracy on validation set
Got 763 / 1000 correct (76.30)

epoch 7, loss = 0.4720
Checking accuracy on validation set
Got 786 / 1000 correct (78.60)

epoch 8, loss = 0.3509
Checking accuracy on validation set
Got 814 / 1000 correct (81.40)

epoch 9, loss = 0.3245
Checking accuracy on validation set
Got 797 / 1000 correct (79.70)

epoch 10, loss = 0.5926
Checking accuracy on validation set
Got 831 / 1000 correct (83.10)



 ## 🎯 Step 8: learning rate 조정 (grid search)

- 모델 구조 유지 후 learning rate 조정
- [5e-5, 1e-4, 5e-4, 1e-3, 5e-3] 범위에서 grid search 진행.



In [43]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model8 = None
optimizer8 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rates = [5e-5, 1e-4, 5e-4, 1e-3, 5e-3]

for learning_rate in learning_rates:
    model8 = nn.Sequential(
        ResBlockBn(in_channels, 64, stride=1),
        ResBlockBn(64, 128, stride=2),
        ResBlockBn(128, 128, stride=1),
        ResBlockBn(128, 256, stride=2),
        ResBlockBn(256, 256, stride=1),
        nn.Flatten(),
        nn.Linear(256 * 8 * 8, 128),
        nn.ReLU(),
        nn.Dropout(p=0.5),
        nn.Linear(128, 10)
    )

    optimizer8 = optim.SGD(model8.parameters(), lr=learning_rate,
                        momentum = 0.9, nesterov=True, weight_decay=1e-3)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
    train_part5(model8, optimizer8, epochs=10, print_per_epoch=True)
    print(f"lr = {learning_rate:.1e} : ")
    check_accuracy_part34(loader_val, model8)
    print()

epoch 1, loss = 1.8355
Checking accuracy on validation set
Got 412 / 1000 correct (41.20)

epoch 2, loss = 1.7582
Checking accuracy on validation set
Got 476 / 1000 correct (47.60)

epoch 3, loss = 1.5670
Checking accuracy on validation set
Got 529 / 1000 correct (52.90)

epoch 4, loss = 1.4435
Checking accuracy on validation set
Got 552 / 1000 correct (55.20)

epoch 5, loss = 1.0445
Checking accuracy on validation set
Got 562 / 1000 correct (56.20)

epoch 6, loss = 1.1608
Checking accuracy on validation set
Got 578 / 1000 correct (57.80)

epoch 7, loss = 1.4042
Checking accuracy on validation set
Got 594 / 1000 correct (59.40)

epoch 8, loss = 0.9568
Checking accuracy on validation set
Got 608 / 1000 correct (60.80)

epoch 9, loss = 1.4005
Checking accuracy on validation set
Got 619 / 1000 correct (61.90)

epoch 10, loss = 1.1879
Checking accuracy on validation set
Got 639 / 1000 correct (63.90)

lr = 5.0e-05 : 
Checking accuracy on validation set
Got 639 / 1000 correct (63.90)

epoch


- **실험 결과**
 - best val_acc = 82.2% (lr = 5e-3)
 - Step 7에서 lr = 1e-3 일 때 val_acc = 83.1% 까지 기록했었기 때문에 좁은 범위에서 다시 한 번 grid search 진행.


- lr = [1e-3, 3e-3, 5e-3, 7e-3]의 범위에서 grid search 재진행.

In [44]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model8 = None
optimizer8 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rates = [1e-3, 3e-3, 5e-3, 7e-3]

for learning_rate in learning_rates:
    model8 = nn.Sequential(
        ResBlockBn(in_channels, 64, stride=1),
        ResBlockBn(64, 128, stride=2),
        ResBlockBn(128, 128, stride=1),
        ResBlockBn(128, 256, stride=2),
        ResBlockBn(256, 256, stride=1),
        nn.Flatten(),
        nn.Linear(256 * 8 * 8, 128),
        nn.ReLU(),
        nn.Dropout(p=0.5),
        nn.Linear(128, 10)
    )

    optimizer8 = optim.SGD(model8.parameters(), lr=learning_rate,
                        momentum = 0.9, nesterov=True, weight_decay=1e-3)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
    train_part5(model8, optimizer8, epochs=10, print_per_epoch=True)
    print(f"lr = {learning_rate:.1e} : ")
    check_accuracy_part34(loader_val, model8)
    print()

epoch 1, loss = 1.4980
Checking accuracy on validation set
Got 571 / 1000 correct (57.10)

epoch 2, loss = 1.4022
Checking accuracy on validation set
Got 678 / 1000 correct (67.80)

epoch 3, loss = 0.6976
Checking accuracy on validation set
Got 708 / 1000 correct (70.80)

epoch 4, loss = 0.9134
Checking accuracy on validation set
Got 730 / 1000 correct (73.00)

epoch 5, loss = 0.7307
Checking accuracy on validation set
Got 783 / 1000 correct (78.30)

epoch 6, loss = 0.6719
Checking accuracy on validation set
Got 778 / 1000 correct (77.80)

epoch 7, loss = 0.7242
Checking accuracy on validation set
Got 824 / 1000 correct (82.40)

epoch 8, loss = 0.4923
Checking accuracy on validation set
Got 799 / 1000 correct (79.90)

epoch 9, loss = 0.3738
Checking accuracy on validation set
Got 791 / 1000 correct (79.10)

epoch 10, loss = 0.5901
Checking accuracy on validation set
Got 819 / 1000 correct (81.90)

lr = 1.0e-03 : 
Checking accuracy on validation set
Got 819 / 1000 correct (81.90)

epoch


- **실험 결과**
 - best val_acc = 84.1% (lr = 3e-3)
 - 최종 learning rate = 3e-3 으로 결정.

 ## 🎯 Step 9: 최종 모델 학습

- learning rate = 3e-3 으로 최종 모델 학습 진행.
- epoch = 15 설정.



In [46]:
################################################################################
# TODO:                                                                        #
# Experiment with any architectures, optimizers, and hyperparameters.          #
# Achieve AT LEAST 70% accuracy on the *validation set* within 10 epochs.      #
#                                                                              #
# Note that you can use the check_accuracy function to evaluate on either      #
# the test set or the validation set, by passing either loader_test or         #
# loader_val as the second argument to check_accuracy. You should not touch    #
# the test set until you have finished your architecture and  hyperparameter   #
# tuning, and only run the test set once at the end to report a final value.   #
################################################################################

model9 = None
optimizer9 = None

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

in_channels = 3
learning_rate = 3e-3

model9 = nn.Sequential(
    ResBlockBn(in_channels, 64, stride=1),
    ResBlockBn(64, 128, stride=2),
    ResBlockBn(128, 128, stride=1),
    ResBlockBn(128, 256, stride=2),
    ResBlockBn(256, 256, stride=1),
    nn.Flatten(),
    nn.Linear(256 * 8 * 8, 128),
    nn.ReLU(),
    nn.Dropout(p=0.5),
    nn.Linear(128, 10)
)

optimizer9 = optim.SGD(model9.parameters(), lr=learning_rate,
                    momentum = 0.9, nesterov=True, weight_decay=1e-3)

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

# You should get at least 70% accuracy.
# You may modify the number of epochs to any number below 15.
train_part5(model9, optimizer9, epochs=15, print_per_epoch=True)

epoch 1, loss = 1.7130
Checking accuracy on validation set
Got 581 / 1000 correct (58.10)

epoch 2, loss = 1.3585
Checking accuracy on validation set
Got 623 / 1000 correct (62.30)

epoch 3, loss = 0.8634
Checking accuracy on validation set
Got 702 / 1000 correct (70.20)

epoch 4, loss = 0.8865
Checking accuracy on validation set
Got 721 / 1000 correct (72.10)

epoch 5, loss = 0.6596
Checking accuracy on validation set
Got 787 / 1000 correct (78.70)

epoch 6, loss = 0.9005
Checking accuracy on validation set
Got 787 / 1000 correct (78.70)

epoch 7, loss = 0.6673
Checking accuracy on validation set
Got 814 / 1000 correct (81.40)

epoch 8, loss = 0.2644
Checking accuracy on validation set
Got 792 / 1000 correct (79.20)

epoch 9, loss = 0.4190
Checking accuracy on validation set
Got 830 / 1000 correct (83.00)

epoch 10, loss = 0.4676
Checking accuracy on validation set
Got 841 / 1000 correct (84.10)

epoch 11, loss = 0.2585
Checking accuracy on validation set
Got 839 / 1000 correct (83.90

## Describe what you did

In the cell below you should write an explanation of what you did, any additional features that you implemented, and/or any graphs that you made in the process of training and evaluating your network.

**Answer:**


- ### 모델 구조

 - **Residual Block × 5**  
  Each block consists of:  
  `Conv → ReLU → Conv → (+ Identity) → ReLU`

 - **Fully Connected Layers**  
  `→ Flatten → FC → ReLU → Dropout → FC → Softmax`


- ### Training Settings

 - Optimizer: SGD + Nesterov Momentum  
 - Learning Rate: `3e-3`  
 - Weight Decay (L2 Regularization): `1e-3`  
 - Dropout Probability: `0.5`  
 - Epochs: `15`  
 - Batch Normalization: Applied after each Conv in residual blocks





## Test set -- run this only once

Now that we've gotten a result we're happy with, we test our final model on the test set (which you should store in best_model). Think about how this compares to your validation set accuracy.

In [48]:
best_model = model9
check_accuracy_part34(loader_test, best_model)

Checking accuracy on test set
Got 8327 / 10000 correct (83.27)
